### ISSUE TITLE
Error: raise ValueError("Axis limits cannot be NaN or Inf")

### ISSUE THREAD

**Issue by wennycooper** [IRMVLab/EfficientLO-Net#6]
I tried to run command/sh with test mode with the pretrained model but I got following error.  Is there anybody help please?

```
run_time_batch: 8 0.20862388610839844/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "./kitti_evaluation.py", line 632, in <module>
    pose_eval.eval(toCameraCoord=args.toCameraCoord)   # set the value according to the predicted results
  File "./kitti_evaluation.py", line 614, in eval
    self.plotError_segment(seq, avg_segment_errs, eva_seq_dir)
  File "./kitti_evaluation.py", line 438, in plotError_segment
    plt.axis([100, np.max(plot_x), 0, np.max(plot_y_t)*(1+0.1)])
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 2437, in axis
    return gca().axis(*v, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_base.py", line 1714, in axis
    self.set_ylim([v[2], v[3]], emit=emit, auto=False)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_base.py", line 3468, in set_ylim
    top = self._validate_converted_limits(top, self.convert_yunits)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_base.py", line 3053, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

```

**Comment by wennycooper** [comment]
I found the problem is there are "nan" values in some the prediction.
For exampe:

```
$ less 00_pred.txt
... [ignored] ...
0.68522955 -0.71344915 0.14648663 5685994601800475076460544.00000000 -0.72008426 -0.63344252 0.28325816 12402092116017648202940416.00000000 -0.10929918 -0.29957919 -0.94779362 8595412177163740124282880.00000000
0.65193995 -0.75768317 0.02996824 5685994601800475076460544.00000000 -0.72637053 -0.61267700 0.31147825 12402092116017648202940416.00000000 -0.21764035 -0.22483303 -0.94978394 8595412177163740124282880.00000000
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan
```
